### ISSUE TITLE
Problems with Custom Data Segmentation in lidar-processingV2 Using Hesai XT32

### ISSUE THREAD

**Issue by thomasankara** [YevgeniyEngineer/LiDAR-Processing-V2#2]
Hello,

I recently tested your package lidar-processingV2, and it works very well with your dataset. However, when I tested it with my data, I encountered some issues that I would like to discuss with you. I am using a Hesai XT32. As you can see from the image I shared, it fails to segment correctly (I am not getting results as good as yours). I have several hypotheses to explain this:

![Screenshot from 2024-06-24 12-11-31](https://github.com/YevgeniyEngineer/LiDAR-Processing-V2/assets/156187785/83e7102a-bf21-4c03-933d-be616266536e)

1. It may be related to this error message I receive when I launch the dataloader: 
   `[dataloader-1] Failed to find match for field 'intensity'`
2. My rosbag was recorded with the LiDAR at a height of 70 cm.
3. There might be a possible configuration adjustment needed in one of the package's files.

Thank you for the work you have done and the quality of the package you offer. Version 2 was much easier to install and use than Version 1.

Best regards.

**Comment by YevgeniyEngineer** [comment]
Hello, @thomasankara 

Thanks for taking your time to install and setup this software on your environment.

Please let me assist you with your concerns.

> I am using a Hesai XT32

As far as I understand, Hesai XT32 is a 32-channel spinning LiDAR. This means that the default settings that are currently hard-coded in the segmentation configuration won't suit your use case. From https://www.hesaitech.com/product/xt32/ I see that LiDAR has 0.18 degree azimuth resolution, and 1 degree vertical resolution, with the field of view ranging from -16 to 15 degrees. Currently I did not have time to expose configuration to the user, but for simplicity you can adjust the hardcoded values as following:

In segmenter.hpp adjust as following:
1. ELEVATION_UP_DEG = +15.1F;
2. ELEVATION_DOWN_DEG = -16.1F;
3. IMAGE_WIDTH = 360.0 / 0.18 = 2000.0F;
4. IMAGE_HEIGHT = 32;

You noted that your sensor is positioned at 70cm above the ground. This will necessitate adjusting the following in segmenter.hpp:
1. sensor_height_m = 0.7F;
2. grid_radial_spacing_m = 3.0F; # this is optional, configure this parameter based on your LiDAR settings.

Now, what data format are you using for publishing the point cloud message?

Note, I currently enabled the message reception for only PointXYZIR (x, y, z, intensity, ring index), and this is the required input format to ensure you can run the pipeline. However, I am planning of templating this pipeline to enable point cloud formats (x, y, z), or (x, y, z, intensity), or (x, y, z, ring index), or (x, y, z, intensity, ring index). However, I will need some time to actually adjust the code to enable this feature.

If you receive this message [dataloader-1] Failed to find match for field 'intensity' it means that the point cloud format you are loading (presumably from .pcd files) is not matching the expected data format that is currently processed by the dataloader node. 

![Screenshot from 2024-06-24 22-12-43](https://github.com/YevgeniyEngineer/LiDAR-Processing-V2/assets/118203812/74ec931f-1ab9-4556-bb9e-70395d199a3a)


As you can see, the PCD data format that dataloader expects is not flexible in my current implementation - it contains (x, y, z, intensity), and ring index is added **dynamically**, but assuming there at 64 rings in the point cloud which is the characteristics of Velodyne - HDL64, which is not true in your case. You can create a custom dataloader for your specific case, or modify my dataloader on this line to load exactly 32 rings (set the value to 31):

![Screenshot from 2024-06-24 22-10-21](https://github.com/YevgeniyEngineer/LiDAR-Processing-V2/assets/118203812/ad8da21a-29ac-486e-9e36-3ec427ff8db5)

Please note, that dataloader is only compatible with PCD files, so the PointCloud2 message that is loaded from ROS2 bag should match the data format input to `processor.cpp` - you may need to modify this loop to convert from `PointCloud2` to `pcl::PointCloud<PointT>`:

![Screenshot from 2024-06-24 22-15-24](https://github.com/YevgeniyEngineer/LiDAR-Processing-V2/assets/118203812/33e63846-10b1-4940-819a-85abb9b5cd99)

Please let me know if I can help you with adjusting the pipeline for your specific use case, I am currently working on refactoring and improving the public usage, separating library files from ROS2 nodes.


Please note, that first step, before you attempt any major changes is to ensure that data is loaded correctly - you will need to view RingsCloud or OrganizedCloud (or create a separate topic for you message type) to view if cloud matches expected cloud.

**Comment by YevgeniyEngineer** [comment]
@thomasankara I refactored the code to enable processing of various point types, such as:

1.) x, y, z
2.) x, y, z, i
3.) x, y, z, ring
4.) x, y, z, i, ring

The processor code will dynamically identify the type and run segmentation pipeline with the point cloud variant.

I also exposed the configuration from segmentation and clustering pipelines - this will enable you to configure settings as needed.

See https://github.com/YevgeniyEngineer/LiDAR-Processing-V2/pull/3#issue-2378773925
